### ISSUE TITLE
Next: Merging effort

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/rules_dotnet#275]
This issue is just an overview of the tasks that need to be done to merge features from the following repositories:
* bazelbuild/rules_dotnet - This repo
* AFASResearch/rules_dotnet - https://github.com/AFASResearch/rules_dotnet
* Brightspace/rules_csharp - https://github.com/Brightspace/rules_csharp
* samhowes/rules_msbuild - https://github.com/samhowes/rules_msbuild

We are expecting some breaking changes but the migration should be pretty straight forward for users of bazelbuild/rules_dotnet and Brightspace/rules_csharp.

## Tasks

The plan is to use Brightspace/rules_csharp as a base and then port features from each ruleset into the base. 
After the initial tasks have been finished the features can be worked on in parallel so don't be shy and contribute if you can!

If you notice any missing task then comment on this issue and I'll add it to the list.

### Initial tasks

- [ ] Create a `next` branch in bazelbuild/rules_dotnet
- [ ] Copy the rule implementations from Brightspace/rules_csharp

### Features

- [ ] Migrate manifest loader from `AFASResearch/rules_dotnet`
- [ ] Migrate apphost shimming from `AFASResearch/rules_dotnet`
- [ ] Get `bazel run` and `bazel test` working for `*_binary1 and `*_nunit_test` rules when targetting .Net core
- [ ] Get `bazel run` and `bazel test` working for `*_binary1 and `*_nunit_test` rules when targetting .Net Framework
    * `Brightspace/rules_csharp` supports targetting .Net Framework and we can keep that functionality if @j3parker and @omsmith deem it necessary
- [ ] Add `*_xunit_test` from `bazelbuild/rules_dotnet`
- [ ] Add proper NuGet support
    * This can be based on @tomdegoede 's work in https://github.com/AFASResearch/bazel-dotnet/tree/master/src/Afas.BazelDotnet.Nuget
- [ ] Add `F#` support from `bazelbuild/rules_dotnet`
- [ ] Add compiler worker support for `C#` from `AFASResearch/rules_dotnet`
- [ ] Add gRPC support to https://github.com/rules-proto-grpc/rules_proto_grpc based on the `next` branch
- [ ] Add Gazelle plugin based on @samhowes `samhowes/rules_msbuild`
- [ ] Add support for selecting .Net SDK version (It's currently hardcoded to .Net 6 in `Brightspace/rules_csharp`)

### Examples

- [ ] Add EntityFramwork example from `bazelbuild/rules_dotnet`
- [ ] Add gRPC example from `bazelbuild/rules_dotnet`
- [ ] Add F# Type Provider example from `bazelbuild/rules_dotnet`
- [ ] Add AspNetCore example

### Docs

- [ ] Update `README.md` on `master` branch to mention the work on the `next` branch
- [ ] Update documentation generation
- [ ] Automatically generate either a Github static site or Github Wiki on merge

**Comment by purkhusid** [comment]
I'm currently working on the initial tasks and hope to have it ready in the next few days.

**Comment by samhowes** [comment]
Happy to work on this! I've had some life changes and a new job recently so I won't be as active as I have been before for a bit. 

I'll try to push a new branch with a start on the Gazelle stuff sometime soon though.

**Comment by purkhusid** [comment]
The initial work has been committed to the `next`branch: https://github.com/bazelbuild/rules_dotnet/tree/next
I also took care of the following items:

* Migrate manifest loader from AFASResearch/rules_dotnet
* Migrate apphost shimming from AFASResearch/rules_dotnet
* Get bazel run and bazel test working for *_binary1 and *_nunit_test` rules when targetting .Net core

**Comment by purkhusid** [comment]
Added F# support to the `next ` branch

**Comment by j3parker** [comment]
> Brightspace/rules_csharp supports targetting .Net Framework and we can keep that functionality if @j3parker and @omsmith deem it necessary

If it's not too hard to maintain I think it would be nice, at least for compilation. I wouldn't bother with running the output personally (e.g. tests) but being able to compile via Bazel on Linux is helpful for D2L and I think not a huge burden to support (just pull in the different reference assembly package.)

**Comment by purkhusid** [comment]
@j3parker Sounds good, it might make sense to add some explicit failures when doing `bazel run` `bazel test` on targets that are targetting .Net Framework then.

**Comment by purkhusid** [comment]
I added Paket support to the `next` branch. This was a good way to verify that the current NuGet rules could be set up with their transitive dependencies correct. The NuGet rules might change a bit once @tomdegoede finishes his version that uses a NuGet lock file and we port it to this repo.

Next week I'm going to see if I can run our internal monorepo using the rules that we have on the `next` branch. We have a good mix of tests/binaries/docker images/F#/C# that should probably surface some bugs.

There are some things I would like to clean up as well:
* Make the SDK version selectable and the SDK list easily updatable (I've got a WIP of this going)
* Add MacOS ARM support (Should be part of the first item in this list)
* See if we can stop parsing the the .Net tar bundles and instead use targetting packs from NuGet. This should make it easier to add new major versions of the SDK.

**Comment by purkhusid** [comment]
I just merged the `next` branch to the `master` branch and created the first release: https://github.com/bazelbuild/rules_dotnet/releases

I'm going to close this issue and create some smaller ones for the rest of the work items.
